-- DROP TABLE DGBIDB.dbo.Bienes_01_BENEFICIARIOS;

CREATE TABLE DGBIDB.dbo.Bienes_01_BENEFICIARIOS (
	id int IDENTITY(1,1) NOT NULL,
	documento_tipo varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	documento varchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	nombre varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	email varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	emailadicional varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	telefono varchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	tipo_persona varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	fechanacimiento datetime NULL,
	sexo char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	activo char(1) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'S' NOT NULL,
	tipo_domicilio varchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	calle varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	piso varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	dpto varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	localidad varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	codigo_postal varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	fecha_registro datetime DEFAULT getdate() NULL,
	row_hash varchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK__Bienes_0__3213E83F327AE2C0 PRIMARY KEY (id)
);


 ALTER TABLE DGBIDB.[dbo].[Bienes_02_CARTERAS] 
    ADD id INT IDENTITY(1,1) NOT NULL;
	
ALTER TABLE DGBIDB.[dbo].[Bienes_02_CARTERAS] 
    ADD CONSTRAINT PK_Bienes_02_CARTERAS PRIMARY KEY (id);	
	
ALTER TABLE DGBIDB.[dbo].[Bienes_02_CARTERAS] 
    ADD row_hash VARCHAR(64) NULL;	
	
	
    CREATE INDEX IX_Bienes_02_CARTERAS_row_hash 
    ON DGBIDB.[dbo].[Bienes_02_CARTERAS] (row_hash);	

    ALTER TABLE DGBIDB.[dbo].[Bienes_02_CARTERAS] 
    ADD fecha_registro DATETIME DEFAULT GETDATE() NULL;

	
	
 ALTER TABLE DGBIDB.[dbo].[Bienes_03_CONTRATOS] 
    ADD id INT IDENTITY(1,1) NOT NULL;
	
ALTER TABLE DGBIDB.[dbo].[Bienes_03_CONTRATOS] 
    ADD CONSTRAINT PK_Bienes_03_CONTRATOS PRIMARY KEY (id);	
	
ALTER TABLE DGBIDB.[dbo].[Bienes_03_CONTRATOS] 
    ADD row_hash VARCHAR(64) NULL;	
	
	
    CREATE INDEX IX_Bienes_03_CONTRATOS_row_hash 
    ON DGBIDB.[dbo].[Bienes_03_CONTRATOS] (row_hash);	

    ALTER TABLE DGBIDB.[dbo].[Bienes_03_CONTRATOS] 
    ADD fecha_registro DATETIME DEFAULT GETDATE() NULL;	
	
	
	
 ALTER TABLE DGBIDB.[dbo].[Bienes_04_PLAN_DE_PAGOS] 
    ADD id INT IDENTITY(1,1) NOT NULL;
	
ALTER TABLE DGBIDB.[dbo].[Bienes_04_PLAN_DE_PAGOS] 
    ADD CONSTRAINT PK_Bienes_04_PLAN_DE_PAGOS PRIMARY KEY (id);	
	
ALTER TABLE DGBIDB.[dbo].[Bienes_04_PLAN_DE_PAGOS] 
    ADD row_hash VARCHAR(64) NULL;	
	
	
    CREATE INDEX IX_Bienes_04_PLAN_DE_PAGOS_row_hash 
    ON DGBIDB.[dbo].[Bienes_04_PLAN_DE_PAGOS] (row_hash);	

   ALTER TABLE DGBIDB.[dbo].[Bienes_04_PLAN_DE_PAGOS] 
    ADD fecha_registro DATETIME DEFAULT GETDATE() NULL;	


    ALTER VIEW VW_Bienes_Carteras AS
    SELECT barrio, ley, identificacion, circunscripcion, seccion, manzana, parcela, division, tipo_unidad, nrounidad, piso, depto, telefono, partidaunidad, digitoverificador, tipoplano, valuacionfiscal, nueva, mtstotales, mtscubiertos, habilitado FROM DGBIDB.dbo.Bienes_02_CARTERAS;

    ALTER VIEW VW_Bienes_Contratos AS    
    SELECT nro, expediente, fechafirma, tipo_contrato, tipo_calculo, tipo_unidad, identificacion, descripcion, nrounidad, vigente, nombre, documento, desde, hasta, principal FROM DGBIDB.dbo.Bienes_03_CONTRATOS;
    
    ALTER VIEW VW_Bienes_Plan_de_pagos AS   
    SELECT tipo, objetivo_prestacion, nombre, documento, email, emailadicional, tipo_persona, calle, carpeta, identificacion, sub_division, nrounidad, tipo_contrato, tipo_calculo, resp_adjudicatatio, documento1, fecha_creacion, nro_expediente, observaciones, numero, vencimiento, fechabui, total, observacion, estado, fechapago, resp_cumplimiento, cuil, legajo FROM DGBIDB.dbo.Bienes_04_PLAN_DE_PAGOS;

    ALTER VIEW VW_Bienes_Beneficiarios AS  
    SELECT documento_tipo, documento, nombre, email, emailadicional, telefono, tipo_persona, fechanacimiento, sexo, activo, tipo_domicilio, calle, piso, dpto, localidad, codigo_postal FROM DGBIDB.dbo.Bienes_01_BENEFICIARIOS;
    
    






	
ALTER TABLE DGBIDB.[dbo].[Concesiones_01_BENEFICIARIOS] 
ADD id INT IDENTITY(1,1) NOT NULL;

ALTER TABLE DGBIDB.[dbo].[Concesiones_01_BENEFICIARIOS] 
ADD CONSTRAINT PK_Concesiones_01_BENEFICIARIOS PRIMARY KEY (id);	

ALTER TABLE DGBIDB.[dbo].[Concesiones_01_BENEFICIARIOS] 
ADD row_hash VARCHAR(64) NULL;	

	
CREATE INDEX IX_Concesiones_01_BENEFICIARIOS_row_hash 
ON DGBIDB.[dbo].[Concesiones_01_BENEFICIARIOS] (row_hash);	

ALTER TABLE DGBIDB.[dbo].[Concesiones_01_BENEFICIARIOS] 
ADD fecha_registro DATETIME DEFAULT GETDATE() NULL;	




ALTER TABLE DGBIDB.[dbo].[Concesiones_02_CARTERAS] 
ADD id INT IDENTITY(1,1) NOT NULL;

ALTER TABLE DGBIDB.[dbo].[Concesiones_02_CARTERAS] 
ADD fecha_registro DATETIME DEFAULT GETDATE() NULL;	

ALTER TABLE DGBIDB.[dbo].[Concesiones_02_CARTERAS] 
ADD CONSTRAINT PK_Concesiones_02_CARTERAS PRIMARY KEY (id);	

ALTER TABLE DGBIDB.[dbo].[Concesiones_02_CARTERAS] 
ADD row_hash VARCHAR(64) NULL;	

CREATE INDEX IX_Concesiones_02_CARTERAS_row_hash 
ON DGBIDB.[dbo].[Concesiones_02_CARTERAS] (row_hash);	


ALTER TABLE DGBIDB.[dbo].[Concesiones_03_CONTRATOS] 
ADD id INT IDENTITY(1,1) NOT NULL;

ALTER TABLE DGBIDB.[dbo].[Concesiones_03_CONTRATOS] 
ADD fecha_registro DATETIME DEFAULT GETDATE() NULL;	

ALTER TABLE DGBIDB.[dbo].[Concesiones_03_CONTRATOS] 
ADD CONSTRAINT PK_Concesiones_03_CONTRATOS PRIMARY KEY (id);	

ALTER TABLE DGBIDB.[dbo].[Concesiones_03_CONTRATOS] 
ADD row_hash VARCHAR(64) NULL;	

CREATE INDEX IX_Concesiones_03_CONTRATOS_row_hash 
ON DGBIDB.[dbo].[Concesiones_03_CONTRATOS] (row_hash);	




ALTER TABLE DGBIDB.[dbo].[Concesiones_04_PLAN_DE_PAGOS] 
ADD id INT IDENTITY(1,1) NOT NULL;


ALTER TABLE DGBIDB.[dbo].[Concesiones_04_PLAN_DE_PAGOS] 
ADD CONSTRAINT PK_Concesiones_04_PLAN_DE_PAGOS PRIMARY KEY (id);	

ALTER TABLE DGBIDB.[dbo].[Concesiones_04_PLAN_DE_PAGOS] 
ADD fecha_registro DATETIME DEFAULT GETDATE() NULL;	

ALTER TABLE DGBIDB.[dbo].[Concesiones_04_PLAN_DE_PAGOS] 
ADD row_hash VARCHAR(64) NULL;	

CREATE INDEX IX_Concesiones_04_PLAN_DE_PAGOS_row_hash 
ON DGBIDB.[dbo].[Concesiones_04_PLAN_DE_PAGOS] (row_hash);	


ALTER TABLE DGBIDB.[dbo].[Concesiones_04_PLAN_DE_PAGOS] 
ADD id INT IDENTITY(1,1) NOT NULL;


ALTER TABLE DGBIDB.[dbo].[Concesiones_04_PLAN_DE_PAGOS] 
ADD CONSTRAINT PK_Concesiones_04_PLAN_DE_PAGOS PRIMARY KEY (id);	

ALTER TABLE DGBIDB.[dbo].[Concesiones_04_PLAN_DE_PAGOS] 
ADD fecha_registro DATETIME DEFAULT GETDATE() NULL;	

ALTER TABLE DGBIDB.[dbo].[Concesiones_04_PLAN_DE_PAGOS] 
ADD row_hash VARCHAR(64) NULL;	


-- Script para agregar columnas id, fecha_registro, row_hash e índices a todas las tablas

-- 01_RELACION_BAC_SIGAF
ALTER TABLE DGBIDB.[dbo].[01_RELACION_BAC_SIGAF] ADD id INT IDENTITY(1,1) NOT NULL;
ALTER TABLE DGBIDB.[dbo].[01_RELACION_BAC_SIGAF] ADD CONSTRAINT PK_01_RELACION_BAC_SIGAF PRIMARY KEY (id);
ALTER TABLE DGBIDB.[dbo].[01_RELACION_BAC_SIGAF] ADD fecha_registro DATETIME DEFAULT GETDATE() NULL;
ALTER TABLE DGBIDB.[dbo].[01_RELACION_BAC_SIGAF] ADD row_hash VARCHAR(64) NULL;
CREATE INDEX IX_01_RELACION_BAC_SIGAF_row_hash ON DGBIDB.[dbo].[01_RELACION_BAC_SIGAF] (row_hash);

-- 02_SPR_RENGLONES
ALTER TABLE DGBIDB.[dbo].[02_SPR_RENGLONES] ADD id INT IDENTITY(1,1) NOT NULL;
ALTER TABLE DGBIDB.[dbo].[02_SPR_RENGLONES] ADD CONSTRAINT PK_02_SPR_RENGLONES PRIMARY KEY (id);
ALTER TABLE DGBIDB.[dbo].[02_SPR_RENGLONES] ADD fecha_registro DATETIME DEFAULT GETDATE() NULL;
ALTER TABLE DGBIDB.[dbo].[02_SPR_RENGLONES] ADD row_hash VARCHAR(64) NULL;
CREATE INDEX IX_02_SPR_RENGLONES_row_hash ON DGBIDB.[dbo].[02_SPR_RENGLONES] (row_hash);

-- 03_SPR_IMPUTACIONES
ALTER TABLE DGBIDB.[dbo].[03_SPR_IMPUTACIONES] ADD id INT IDENTITY(1,1) NOT NULL;
ALTER TABLE DGBIDB.[dbo].[03_SPR_IMPUTACIONES] ADD CONSTRAINT PK_03_SPR_IMPUTACIONES PRIMARY KEY (id);
ALTER TABLE DGBIDB.[dbo].[03_SPR_IMPUTACIONES] ADD fecha_registro DATETIME DEFAULT GETDATE() NULL;
ALTER TABLE DGBIDB.[dbo].[03_SPR_IMPUTACIONES] ADD row_hash VARCHAR(64) NULL;
CREATE INDEX IX_03_SPR_IMPUTACIONES_row_hash ON DGBIDB.[dbo].[03_SPR_IMPUTACIONES] (row_hash);

-- 04_RPR_SPR_PRD
ALTER TABLE DGBIDB.[dbo].[04_RPR_SPR_PRD] ADD id INT IDENTITY(1,1) NOT NULL;
ALTER TABLE DGBIDB.[dbo].[04_RPR_SPR_PRD] ADD CONSTRAINT PK_04_RPR_SPR_PRD PRIMARY KEY (id);
ALTER TABLE DGBIDB.[dbo].[04_RPR_SPR_PRD] ADD fecha_registro DATETIME DEFAULT GETDATE() NULL;
ALTER TABLE DGBIDB.[dbo].[04_RPR_SPR_PRD] ADD row_hash VARCHAR(64) NULL;
CREATE INDEX IX_04_RPR_SPR_PRD_row_hash ON DGBIDB.[dbo].[04_RPR_SPR_PRD] (row_hash);

-- 05_RPR_RENGLONES
ALTER TABLE DGBIDB.[dbo].[05_RPR_RENGLONES] ADD id INT IDENTITY(1,1) NOT NULL;
ALTER TABLE DGBIDB.[dbo].[05_RPR_RENGLONES] ADD CONSTRAINT PK_05_RPR_RENGLONES PRIMARY KEY (id);
ALTER TABLE DGBIDB.[dbo].[05_RPR_RENGLONES] ADD fecha_registro DATETIME DEFAULT GETDATE() NULL;
ALTER TABLE DGBIDB.[dbo].[05_RPR_RENGLONES] ADD row_hash VARCHAR(64) NULL;
CREATE INDEX IX_05_RPR_RENGLONES_row_hash ON DGBIDB.[dbo].[05_RPR_RENGLONES] (row_hash);

-- 06_RPR_IMPUTACIONES
ALTER TABLE DGBIDB.[dbo].[06_RPR_IMPUTACIONES] ADD id INT IDENTITY(1,1) NOT NULL;
ALTER TABLE DGBIDB.[dbo].[06_RPR_IMPUTACIONES] ADD CONSTRAINT PK_06_RPR_IMPUTACIONES PRIMARY KEY (id);
ALTER TABLE DGBIDB.[dbo].[06_RPR_IMPUTACIONES] ADD fecha_registro DATETIME DEFAULT GETDATE() NULL;
ALTER TABLE DGBIDB.[dbo].[06_RPR_IMPUTACIONES] ADD row_hash VARCHAR(64) NULL;
CREATE INDEX IX_06_RPR_IMPUTACIONES_row_hash ON DGBIDB.[dbo].[06_RPR_IMPUTACIONES] (row_hash);


-- 08_PRD_IMPUTACIONES
ALTER TABLE DGBIDB.[dbo].[08_PRD_IMPUTACIONES] ADD id INT IDENTITY(1,1) NOT NULL;
ALTER TABLE DGBIDB.[dbo].[08_PRD_IMPUTACIONES] ADD CONSTRAINT PK_08_PRD_IMPUTACIONES PRIMARY KEY (id);
ALTER TABLE DGBIDB.[dbo].[08_PRD_IMPUTACIONES] ADD fecha_registro DATETIME DEFAULT GETDATE() NULL;
ALTER TABLE DGBIDB.[dbo].[08_PRD_IMPUTACIONES] ADD row_hash VARCHAR(64) NULL;
CREATE INDEX IX_08_PRD_IMPUTACIONES_row_hash ON DGBIDB.[dbo].[08_PRD_IMPUTACIONES] (row_hash);

-- 09_PRD_FACTURAS
ALTER TABLE DGBIDB.[dbo].[09_PRD_FACTURAS] ADD id INT IDENTITY(1,1) NOT NULL;
ALTER TABLE DGBIDB.[dbo].[09_PRD_FACTURAS] ADD CONSTRAINT PK_09_PRD_FACTURAS PRIMARY KEY (id);
ALTER TABLE DGBIDB.[dbo].[09_PRD_FACTURAS] ADD fecha_registro DATETIME DEFAULT GETDATE() NULL;
ALTER TABLE DGBIDB.[dbo].[09_PRD_FACTURAS] ADD row_hash VARCHAR(64) NULL;
CREATE INDEX IX_09_PRD_FACTURAS_row_hash ON DGBIDB.[dbo].[09_PRD_FACTURAS] (row_hash);

-- 10_FACTURAS_OP_PAGOS
ALTER TABLE DGBIDB.[dbo].[10_FACTURAS_OP_PAGOS] ADD id INT IDENTITY(1,1) NOT NULL;
ALTER TABLE DGBIDB.[dbo].[10_FACTURAS_OP_PAGOS] ADD CONSTRAINT PK_10_FACTURAS_OP_PAGOS PRIMARY KEY (id);
ALTER TABLE DGBIDB.[dbo].[10_FACTURAS_OP_PAGOS] ADD fecha_registro DATETIME DEFAULT GETDATE() NULL;
ALTER TABLE DGBIDB.[dbo].[10_FACTURAS_OP_PAGOS] ADD row_hash VARCHAR(64) NULL;
CREATE INDEX IX_10_FACTURAS_OP_PAGOS_row_hash ON DGBIDB.[dbo].[10_FACTURAS_OP_PAGOS] (row_hash);

-- 11_RP
ALTER TABLE DGBIDB.[dbo].[11_RP] ADD id INT IDENTITY(1,1) NOT NULL;
ALTER TABLE DGBIDB.[dbo].[11_RP] ADD CONSTRAINT PK_11_RP PRIMARY KEY (id);
ALTER TABLE DGBIDB.[dbo].[11_RP] ADD fecha_registro DATETIME DEFAULT GETDATE() NULL;
ALTER TABLE DGBIDB.[dbo].[11_RP] ADD row_hash VARCHAR(64) NULL;
CREATE INDEX IX_11_RP_row_hash ON DGBIDB.[dbo].[11_RP] (row_hash);

-- 12_DRP_RENGLONES
ALTER TABLE DGBIDB.[dbo].[12_DRP_RENGLONES] ADD id INT IDENTITY(1,1) NOT NULL;
ALTER TABLE DGBIDB.[dbo].[12_DRP_RENGLONES] ADD CONSTRAINT PK_12_DRP_RENGLONES PRIMARY KEY (id);
ALTER TABLE DGBIDB.[dbo].[12_DRP_RENGLONES] ADD fecha_registro DATETIME DEFAULT GETDATE() NULL;
ALTER TABLE DGBIDB.[dbo].[12_DRP_RENGLONES] ADD row_hash VARCHAR(64) NULL;
CREATE INDEX IX_12_DRP_RENGLONES_row_hash ON DGBIDB.[dbo].[12_DRP_RENGLONES] (row_hash);

-- 13_DRP_IMPUTACIONES
ALTER TABLE DGBIDB.[dbo].[13_DRP_IMPUTACIONES] ADD id INT IDENTITY(1,1) NOT NULL;
ALTER TABLE DGBIDB.[dbo].[13_DRP_IMPUTACIONES] ADD CONSTRAINT PK_13_DRP_IMPUTACIONES PRIMARY KEY (id);
ALTER TABLE DGBIDB.[dbo].[13_DRP_IMPUTACIONES] ADD fecha_registro DATETIME DEFAULT GETDATE() NULL;
ALTER TABLE DGBIDB.[dbo].[13_DRP_IMPUTACIONES] ADD row_hash VARCHAR(64) NULL;
CREATE INDEX IX_13_DRP_IMPUTACIONES_row_hash ON DGBIDB.[dbo].[13_DRP_IMPUTACIONES] (row_hash);

-- 14_DRP_FACTURAS
ALTER TABLE DGBIDB.[dbo].[14_DRP_FACTURAS] ADD id INT IDENTITY(1,1) NOT NULL;
ALTER TABLE DGBIDB.[dbo].[14_DRP_FACTURAS] ADD CONSTRAINT PK_14_DRP_FACTURAS PRIMARY KEY (id);
ALTER TABLE DGBIDB.[dbo].[14_DRP_FACTURAS] ADD fecha_registro DATETIME DEFAULT GETDATE() NULL;
ALTER TABLE DGBIDB.[dbo].[14_DRP_FACTURAS] ADD row_hash VARCHAR(64) NULL;
CREATE INDEX IX_14_DRP_FACTURAS_row_hash ON DGBIDB.[dbo].[14_DRP_FACTURAS] (row_hash);

-- 15_DRP_FACTURAS_PAGOS
ALTER TABLE DGBIDB.[dbo].[15_DRP_FACTURAS_PAGOS] ADD id INT IDENTITY(1,1) NOT NULL;
ALTER TABLE DGBIDB.[dbo].[15_DRP_FACTURAS_PAGOS] ADD CONSTRAINT PK_15_DRP_FACTURAS_PAGOS PRIMARY KEY (id);
ALTER TABLE DGBIDB.[dbo].[15_DRP_FACTURAS_PAGOS] ADD fecha_registro DATETIME DEFAULT GETDATE() NULL;
ALTER TABLE DGBIDB.[dbo].[15_DRP_FACTURAS_PAGOS] ADD row_hash VARCHAR(64) NULL;
CREATE INDEX IX_15_DRP_FACTURAS_PAGOS_row_hash ON DGBIDB.[dbo].[15_DRP_FACTURAS_PAGOS] (row_hash);

-- 16_PRECIARIO
ALTER TABLE DGBIDB.[dbo].[16_PRECIARIO] ADD id INT IDENTITY(1,1) NOT NULL;
ALTER TABLE DGBIDB.[dbo].[16_PRECIARIO] ADD CONSTRAINT PK_16_PRECIARIO PRIMARY KEY (id);
ALTER TABLE DGBIDB.[dbo].[16_PRECIARIO] ADD fecha_registro DATETIME DEFAULT GETDATE() NULL;
ALTER TABLE DGBIDB.[dbo].[16_PRECIARIO] ADD row_hash VARCHAR(64) NULL;
CREATE INDEX IX_16_PRECIARIO_row_hash ON DGBIDB.[dbo].[16_PRECIARIO] (row_hash);

-- 17_PRECIARIO_IMPUTACIONES
ALTER TABLE DGBIDB.[dbo].[17_PRECIARIO_IMPUTACIONES] ADD id INT IDENTITY(1,1) NOT NULL;
ALTER TABLE DGBIDB.[dbo].[17_PRECIARIO_IMPUTACIONES] ADD CONSTRAINT PK_17_PRECIARIO_IMPUTACIONES PRIMARY KEY (id);
ALTER TABLE DGBIDB.[dbo].[17_PRECIARIO_IMPUTACIONES] ADD fecha_registro DATETIME DEFAULT GETDATE() NULL;
ALTER TABLE DGBIDB.[dbo].[17_PRECIARIO_IMPUTACIONES] ADD row_hash VARCHAR(64) NULL;
CREATE INDEX IX_17_PRECIARIO_IMPUTACIONES_row_hash ON DGBIDB.[dbo].[17_PRECIARIO_IMPUTACIONES] (row_hash);

-- 18_PRD_PRECIARIO
ALTER TABLE DGBIDB.[dbo].[18_PRD_PRECIARIO] ADD id INT IDENTITY(1,1) NOT NULL;
ALTER TABLE DGBIDB.[dbo].[18_PRD_PRECIARIO] ADD CONSTRAINT PK_18_PRD_PRECIARIO PRIMARY KEY (id);
ALTER TABLE DGBIDB.[dbo].[18_PRD_PRECIARIO] ADD fecha_registro DATETIME DEFAULT GETDATE() NULL;
ALTER TABLE DGBIDB.[dbo].[18_PRD_PRECIARIO] ADD row_hash VARCHAR(64) NULL;
CREATE INDEX IX_18_PRD_PRECIARIO_row_hash ON DGBIDB.[dbo].[18_PRD_PRECIARIO] (row_hash);

-- 19_PRD_PRECIARIO_RENGLONES
ALTER TABLE DGBIDB.[dbo].[19_PRD_PRECIARIO_RENGLONES] ADD id INT IDENTITY(1,1) NOT NULL;
ALTER TABLE DGBIDB.[dbo].[19_PRD_PRECIARIO_RENGLONES] ADD CONSTRAINT PK_19_PRD_PRECIARIO_RENGLONES PRIMARY KEY (id);
ALTER TABLE DGBIDB.[dbo].[19_PRD_PRECIARIO_RENGLONES] ADD fecha_registro DATETIME DEFAULT GETDATE() NULL;
ALTER TABLE DGBIDB.[dbo].[19_PRD_PRECIARIO_RENGLONES] ADD row_hash VARCHAR(64) NULL;
CREATE INDEX IX_19_PRD_PRECIARIO_RENGLONES_row_hash ON DGBIDB.[dbo].[19_PRD_PRECIARIO_RENGLONES] (row_hash);

-- 20_PRD_PRECIARIO_IMPUTACIONES
ALTER TABLE DGBIDB.[dbo].[20_PRD_PRECIARIO_IMPUTACIONES] ADD id INT IDENTITY(1,1) NOT NULL;
ALTER TABLE DGBIDB.[dbo].[20_PRD_PRECIARIO_IMPUTACIONES] ADD CONSTRAINT PK_20_PRD_PRECIARIO_IMPUTACIONES PRIMARY KEY (id);
ALTER TABLE DGBIDB.[dbo].[20_PRD_PRECIARIO_IMPUTACIONES] ADD fecha_registro DATETIME DEFAULT GETDATE() NULL;
ALTER TABLE DGBIDB.[dbo].[20_PRD_PRECIARIO_IMPUTACIONES] ADD row_hash VARCHAR(64) NULL;
CREATE INDEX IX_20_PRD_PRECIARIO_IMPUTACIONES_row_hash ON DGBIDB.[dbo].[20_PRD_PRECIARIO_IMPUTACIONES] (row_hash);

-- 21_PRD_PRECIARIO_FACTURAS
ALTER TABLE DGBIDB.[dbo].[21_PRD_PRECIARIO_FACTURAS] ADD id INT IDENTITY(1,1) NOT NULL;
ALTER TABLE DGBIDB.[dbo].[21_PRD_PRECIARIO_FACTURAS] ADD CONSTRAINT PK_21_PRD_PRECIARIO_FACTURAS PRIMARY KEY (id);
ALTER TABLE DGBIDB.[dbo].[21_PRD_PRECIARIO_FACTURAS] ADD fecha_registro DATETIME DEFAULT GETDATE() NULL;
ALTER TABLE DGBIDB.[dbo].[21_PRD_PRECIARIO_FACTURAS] ADD row_hash VARCHAR(64) NULL;
CREATE INDEX IX_21_PRD_PRECIARIO_FACTURAS_row_hash ON DGBIDB.[dbo].[21_PRD_PRECIARIO_FACTURAS] (row_hash);

-- 22_PAGOS_PRECIARIO
ALTER TABLE DGBIDB.[dbo].[22_PAGOS_PRECIARIO] ADD id INT IDENTITY(1,1) NOT NULL;
ALTER TABLE DGBIDB.[dbo].[22_PAGOS_PRECIARIO] ADD CONSTRAINT PK_22_PAGOS_PRECIARIO PRIMARY KEY (id);
ALTER TABLE DGBIDB.[dbo].[22_PAGOS_PRECIARIO] ADD fecha_registro DATETIME DEFAULT GETDATE() NULL;
ALTER TABLE DGBIDB.[dbo].[22_PAGOS_PRECIARIO] ADD row_hash VARCHAR(64) NULL;
CREATE INDEX IX_22_PAGOS_PRECIARIO_row_hash ON DGBIDB.[dbo].[22_PAGOS_PRECIARIO] (row_hash);

-- 23_UNIDADES_EJECUTORAS
ALTER TABLE DGBIDB.[dbo].[23_UNIDADES_EJECUTORAS] ADD id INT IDENTITY(1,1) NOT NULL;
ALTER TABLE DGBIDB.[dbo].[23_UNIDADES_EJECUTORAS] ADD CONSTRAINT PK_23_UNIDADES_EJECUTORAS PRIMARY KEY (id);
ALTER TABLE DGBIDB.[dbo].[23_UNIDADES_EJECUTORAS] ADD fecha_registro DATETIME DEFAULT GETDATE() NULL;
ALTER TABLE DGBIDB.[dbo].[23_UNIDADES_EJECUTORAS] ADD row_hash VARCHAR(64) NULL;
CREATE INDEX IX_23_UNIDADES_EJECUTORAS_row_hash ON DGBIDB.[dbo].[23_UNIDADES_EJECUTORAS] (row_hash);

-- 24_PERIODOS_FISCALES
ALTER TABLE DGBIDB.[dbo].[24_PERIODOS_FISCALES] ADD id INT IDENTITY(1,1) NOT NULL;
ALTER TABLE DGBIDB.[dbo].[24_PERIODOS_FISCALES] ADD CONSTRAINT PK_24_PERIODOS_FISCALES PRIMARY KEY (id);
ALTER TABLE DGBIDB.[dbo].[24_PERIODOS_FISCALES] ADD fecha_registro DATETIME DEFAULT GETDATE() NULL;
ALTER TABLE DGBIDB.[dbo].[24_PERIODOS_FISCALES] ADD row_hash VARCHAR(64) NULL;
CREATE INDEX IX_24_PERIODOS_FISCALES_row_hash ON DGBIDB.[dbo].[24_PERIODOS_FISCALES] (row_hash);

-- 25_ENTES
ALTER TABLE DGBIDB.[dbo].[25_ENTES] ADD id INT IDENTITY(1,1) NOT NULL;
ALTER TABLE DGBIDB.[dbo].[25_ENTES] ADD CONSTRAINT PK_25_ENTES PRIMARY KEY (id);
ALTER TABLE DGBIDB.[dbo].[25_ENTES] ADD fecha_registro DATETIME DEFAULT GETDATE() NULL;
ALTER TABLE DGBIDB.[dbo].[25_ENTES] ADD row_hash VARCHAR(64) NULL;
CREATE INDEX IX_25_ENTES_row_hash ON DGBIDB.[dbo].[25_ENTES] (row_hash);


ALTER TABLE DGBIDB.dbo.[04_RPR_SPR_PRD] ALTER COLUMN n_ocompra varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL;

ALTER TABLE DGBIDB.dbo.[15_DRP_FACTURAS_PAGOS]
ALTER COLUMN ia_pagado varchar(20) NULL;

ALTER TABLE DGBIDB.dbo.[15_DRP_FACTURAS_PAGOS]
ALTER COLUMN importe_neto varchar(20) NULL;

ALTER TABLE DGBIDB.dbo.[15_DRP_FACTURAS_PAGOS]
ALTER COLUMN importe_op varchar(20) NULL;

ALTER TABLE DGBIDB.dbo.[15_DRP_FACTURAS_PAGOS]
ALTER COLUMN ia_pagado varchar(20) NULL;

ALTER TABLE DGBIDB.dbo.[15_DRP_FACTURAS_PAGOS]
ALTER COLUMN importe_neto varchar(20) NULL;

-- 07_PRD_RENGLONES
ALTER TABLE DGBIDB.[dbo].[07_PRD_RENGLONES] ADD id INT IDENTITY(1,1) NOT NULL;
ALTER TABLE DGBIDB.[dbo].[07_PRD_RENGLONES] ADD CONSTRAINT PK_07_PRD_RENGLONES PRIMARY KEY (id);
ALTER TABLE DGBIDB.[dbo].[07_PRD_RENGLONES] ADD fecha_registro DATETIME DEFAULT GETDATE() NULL;
ALTER TABLE DGBIDB.[dbo].[07_PRD_RENGLONES] ADD row_hash VARCHAR(64) NULL;
CREATE INDEX IX_07_PRD_RENGLONES_row_hash ON DGBIDB.[dbo].[07_PRD_RENGLONES] (row_hash);


CREATE TABLE DGBIDB.dbo.[07_PRD_RENGLONES] (
	aa_oca_original varchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	n_oca_original varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	o_ente varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	i_total_adjudicacion decimal(15,2) NULL,
	aa_precepcion varchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	t_precepcion varchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	n_precepcion varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	aa_rprovision varchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	t_rprovision varchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	n_rprovision varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	e_formulario char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	f_desde varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	f_hasta varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	c_unid_ejec varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	n_renglon_pliego varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	k_rdefinitiva decimal(15,6) NULL,
	i_unitario decimal(15,2) NULL,
	total_renglon decimal(15,2) NULL,
	fh_alta varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	fh_autorizacion varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	fh_firma varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	t_precepcion_1 varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
);