SELECT DISTINCT f.AA_OCOMPRA ,f.N_OCOMPRA ,f.AA_CERTIFICADO
,f.T_FORM_MEDICION ,f.O_CERTIFICADO 
,f.AA_FACTURA ,f.O_FACTURA ,f.T_FACTURA ,f.E_FACTURA ,f.T_FACT_PROVEEDOR ,f.N_SUC_FACT_PROVEEDOR ,f.N_FACT_PROVEEDOR
,f.F_FACTURA ,f.FH_ALTA ,f.F_AUTORIZACION 
,f_ffi.C_NUMCRED
,f.C_JURIS ,f.C_SJURIS ,f.C_ENTIDAD
,imp.C_PROGRAMA ,imp.C_INCISO ,imp.C_PPRINCIPAL ,imp.C_PPARCIAL ,imp.C_PSPARCIAL /*C_PPARCIAL_1*/ ,imp.C_UBICA_GEO
,f_ffi.I_DEVENGADO
,f_ffi.I_PAGADO
FROM slu.TFACTURA_GS f, slu.TDEVENGADO dv, slu.DDEV_RPR_REDET_REN dv_rpr_rd, slu.DFACGS_FFI f_ffi, slu.timput_cred imp
WHERE f.AA_CERTIFICADO = dv.AA_DEVENGADO AND f.T_FORM_MEDICION = dv.T_DEVENGADO AND f.O_CERTIFICADO = N_DEVENGADO 
AND dv_rpr_rd.O_DEVENGADO = dv.O_DEVENGADO
AND f.AA_FACTURA = f_ffi.AA_FACTURA AND f.O_FACTURA = f_ffi.O_FACTURA 
AND imp.AA_EJERVG = f_ffi.AA_factura AND imp.C_NUMCRED = f_ffi.C_NUMCRED 
AND f.T_FACTURA = 'FRP' AND dv_rpr_rd.c_clase IN (990010,560000,790000);