SELECT dv.AA_OCOMPRA ,dv.N_OCOMPRA ,dv.AA_DEVENGADO ,dv.T_DEVENGADO ,dv.N_DEVENGADO ,dv.O_ENTE
,dv_rpr_rd.T_RPROVISION ,dv_rpr_rd.AA_RPROVISION ,dv_rpr_rd.N_RPROVISION ,rd.N_ORDEN_REDET
,dv_rpr_rd.N_RENGLON_PLIEGO
,dv_rpr_rd.K_RDEFINITIVA
,dv_rpr_rd.I_VARIACION
,dv.E_DEVENGADO ,dv.FH_ALTA ,dv.F_AUTORIZACION ,dv.FH_FIRMA ,dv_rpr_rd.O_REDETERMINACION
FROM slu.TDEVENGADO dv
JOIN slu.DDEV_RPR_REDET_REN dv_rpr_rd ON dv_rpr_rd.O_DEVENGADO = dv.O_DEVENGADO 
JOIN slu.tredeterminacion rd ON dv_rpr_rd.O_REDETERMINACION = rd.O_REDETERMINACION 
WHERE dv_rpr_rd.c_clase IN (990010,560000,790000);